### ISSUE TITLE
Keep Generating parent span container for code snippet

### ISSUE THREAD

**Issue by laksmaria** [simonkberg/react-hljs#2]
Keep Generating parent span container for code snippet which has been included through highlight component.

For ex: my code is 
                    Transfer transfer = Transfer.create(new NestedPropertiesMap()
                        .set('amount', 1000L)
                        .set('type', 'C2C')
                        .set('currency', 'USD')
                        .set('sender.first_name', 'John')
                        .set('sender.last_name', 'Tyler')
                    );

But it does comes out as 

.set(<span class="hljs-string" contenteditable="true"><span class="hljs-string" contenteditable="true"><span class="hljs-string"><span class="hljs-string">'amount'</span></span></span></span>, <span class="hljs-number"><span class="hljs-number"><span class="hljs-number"><span class="hljs-number">1000L</span></span></span></span>) 

So for hljs-number element has four child spans.

**Comment by simonkberg** [comment]
https://github.com/simonkberg/react-hljs#deprecated
